/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
   @Test
  public void testAddVertexTograph1(){
     Graph graph = new Graph();

     graph.addVertex("sanabel");
     graph.addVertex("ahmad");
     graph.addVertex("tareq");
     graph.addVertex("yasmeen");
     graph.addVertex("kamleh");
     graph.addVertex("jamal");

     assertEquals("{Vertex{value='tareq'}=[], Vertex{value='jamal'}=[], Vertex{value='yasmeen'}=[], Vertex{value='kamleh'}=[], Vertex{value='sanabel'}=[], Vertex{value='ahmad'}=[]}",graph.getAdjVertices().toString());
   }
   @Test
  public void testEmptygraph(){
     Graph graph = new Graph();
    assertEquals("{}",graph.getAdjVertices().toString());
  }
  @Test
  public void testSizeOfgraph3(){
    Graph graph = new Graph();
    graph.addVertex("sanabel");
    graph.addVertex("ahmad");
    graph.addVertex("tareq");
    graph.addVertex("yasmeen");
    graph.addVertex("kamleh");
    graph.addVertex("jamal");
    assertEquals(6,graph.size());

  }
  @Test
  public void testAddEdgeTograph4(){
    Graph graph = new Graph();

    graph.addVertex("sanabel");
    graph.addVertex("ahmad");
    graph.addVertex("tareq");
    graph.addVertex("yasmeen");
    graph.addVertex("kamleh");
    graph.addVertex("jamal");

    graph.addEdge("jamal", "kamleh");
    graph.addEdge("kamleh", "sanabel");
    graph.addEdge("sanabel", "yasmeen");

    assertEquals("{Vertex{value='tareq'}=[], Vertex{value='jamal'}=[Vertex{value='kamleh'}], Vertex{value='yasmeen'}=[Vertex{value='sanabel'}], Vertex{value='kamleh'}=[Vertex{value='jamal'}, Vertex{value='sanabel'}], Vertex{value='sanabel'}=[Vertex{value='kamleh'}, Vertex{value='yasmeen'}], Vertex{value='ahmad'}=[]}",graph.getAdjVertices().toString());


  }
  @Test
  public void testGetNighborsgraph5(){
    Graph graph = new Graph();

    graph.addVertex("sanabel");
    graph.addVertex("ahmad");
    graph.addVertex("tareq");
    graph.addVertex("yasmeen");
    graph.addVertex("kamleh");
    graph.addVertex("jamal");

    graph.addEdge("jamal", "kamleh");
    graph.addEdge("kamleh", "sanabel");
    graph.addEdge("sanabel", "yasmeen");

    assertEquals("[Vertex{value='kamleh'}, Vertex{value='yasmeen'}]",graph.getNeighborsForVertex("sanabel").toString());


  }
}
