/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
  public static void main(String[] args) {

    int[] array = {55,76,47,36,12,32,22,52};
    int n = array.length;

    QuickSort.quickSort(array, 0, n - 1);
    System.out.print("Quick Sort array: [");

    for (int i = 0; i < n; i++) {
      System.out.print(array[i] + " ");
    }
    System.out.println("]");
  }

}
