/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
  @Test public void testReapating1() {
    Reapeating reapeating = new Reapeating();
    String test = "Once upon a time, there was a brave princess who...";
    assertEquals("a", Reapeating.repeitingWords(test));
  }
  @Test public void testReapating2() {
    Reapeating reapeating = new Reapeating();
    String test = "it was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only...";
    assertEquals("it", Reapeating.repeitingWords(test));
  }
  @Test public void testReapating3() {
    Reapeating reapeating = new Reapeating();
    String test = "It a queer, sultry summer , summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...";
    assertEquals("summer", Reapeating.repeitingWords(test));
  }
  @Test public void testReapating4() {
    Reapeating reapeating = new Reapeating();
    String test = "Once upon a time, there was  brave princess who...";
    assertEquals("Try Again ,No Repeating Words", Reapeating.repeitingWords(test));
  }
}
