/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
  public static void main(String[] args) {
    HashTable<String, Integer> books = new HashTable<>();

    books.add("The Great Gatsby",2);
    books.add("Passage to India", 5);
    books.add("Beloved", 7);
    books.add("To Kill a Mockingbird", 9);

    books.hash("To Kill a Mockingbird");
    System.out.println( "hash : "+books.hash("The Great Gatsby"));

    System.out.println("get value after added: "+books.get("The Great Gatsby"));

    System.out.println("false: because the book not added ...."+books.contains("Anna Karenina"));
    System.out.println("true: because the book is added ...."+books.contains("Beloved"));
  }

}
