import java.util.ArrayList;
import java.util.List;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
  public static void main(String[] args) {

      Graph graph = new Graph();

      graph.addVertex("sanabel");
      graph.addVertex("ahmad");
      graph.addVertex("tareq");
      graph.addVertex("yasmeen");
      graph.addVertex("kamleh");
      graph.addVertex("jamal");

      graph.addEdge("jamal", "kamleh");
      graph.addEdge("kamleh", "sanabel");
      graph.addEdge("sanabel", "yasmeen");
      graph.addEdge("tareq", "ahmad");
      graph.addEdge("ahmad", "yasmeen");
      graph.addEdge("tareq", "yasmeen");

      System.out.println(" print vertex in the graph: "+graph.getAdjVertices());
      System.out.println(" size (num of vertex ) in graph: "+graph.size());
      System.out.println(" get the Neighbors in graph: "+graph.getNeighborsForVertex("jamal"));
      System.out.println(" get the Neighbors in graph: "+graph.getNeighborsForVertex("sanabel"));
      System.out.println(" get the Neighbors in graph: "+graph.getNeighborsForVertex("ahmad"));

           /////////////////////cc36///////////////////////////

    Graph graph2 = new Graph();

    graph2.addVertex("Pandora");
    graph2.addVertex("Arendelle");
    graph2.addVertex("Metroville");
    graph2.addVertex("Monstroplolis");
    graph2.addVertex("Narnia");
    graph2.addVertex("Naboo");

    graph2.addEdge("Pandora", "Arendelle");
    graph2.addEdge("Arendelle", "Metroville");
    graph2.addEdge("Arendelle", "Monstroplolis");
    graph2.addEdge("Metroville", "Narnia");
    graph2.addEdge("Monstroplolis", "Metroville");
    graph2.addEdge("Naboo", "Narnia");
    graph2.addEdge("Naboo", "Metroville");
    graph2.addEdge("Naboo", "Monstroplolis");

    System.out.println(" print graph Breadth First: "+graph2.graphBreadthFirst(graph2,"Pandora"));
    System.out.println(" print graph Breadth First: "+graph2.graphBreadthFirst(graph2,"Arendelle"));

                   /////////////////////cc37///////////////////////////
    Graph graph3 = new Graph();

    graph3.addVertex("Pandora");
    graph3.addVertex("Arendelle");
    graph3.addVertex("Metroville");
    graph3.addVertex("Monstroplolis");
    graph3.addVertex("Narnia");
    graph3.addVertex("Naboo");

    graph3.addEdgeWithWeight("Pandora", "Arendelle",150);
    graph3.addEdgeWithWeight("Arendelle", "Metroville",82);
    graph3.addEdgeWithWeight("Arendelle", "Monstroplolis",42);
    graph3.addEdgeWithWeight("Metroville", "Narnia",37);
    graph3.addEdgeWithWeight("Arendelle", "Metroville",99);
    graph3.addEdgeWithWeight("Monstroplolis", "Metroville",105);
    graph3.addEdgeWithWeight("Naboo", "Narnia",250);
    graph3.addEdgeWithWeight("Naboo", "Metroville",26);
    graph3.addEdgeWithWeight("Naboo", "Monstroplolis",73);

    List<String> listOfTrips = new ArrayList<>();

    listOfTrips.add("Pandora");
    listOfTrips.add("Arendelle");

    List<String> listOfTrips2 = new ArrayList<>();
    listOfTrips2.add("Naboo");
    listOfTrips2.add("Narnia");
    listOfTrips2.add("Metroville");
    listOfTrips2.add("Monstroplolis");

    List<String> listOfTrips3 = new ArrayList<>();
    listOfTrips3.add("Pandora");
    listOfTrips3.add("Naboo");

    System.out.println("Total price for Trip #1: "+graph3.businessTrip(graph3,listOfTrips));
    System.out.println("Total price for Trip #2: "+graph3.businessTrip(graph3,listOfTrips2));
    System.out.println("Total price for Trip #3: "+graph3.businessTrip(graph3,listOfTrips3));

             /////////////////////cc38///////////////////////////
    Graph graph4 = new Graph();

    graph4.addVertex("A");
    graph4.addVertex("B");
    graph4.addVertex("C");
    graph4.addVertex("D");
    graph4.addVertex("E");
    graph4.addVertex("F");
    graph4.addVertex("G");
    graph4.addVertex("H");

    graph4.addEdge("A", "B");
    graph4.addEdge("A", "D");
    graph4.addEdge("B", "C");
    graph4.addEdge("B", "D");
    graph4.addEdge("C", "G");
    graph4.addEdge("D", "F");
    graph4.addEdge("D", "H");
    graph4.addEdge("D", "E");
    graph4.addEdge("F", "H");

    System.out.println(" print graph depth First: "+graph4.depthFirst(graph4,"A"));
    System.out.println(" print graph depth First: "+graph4.depthFirst(graph4,"B"));


  }

}
