import java.util.List;
import java.util.Vector;
import sun.security.provider.certpath.Vertex;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
  public static void main(String[] args) {

      Graph graph = new Graph();

      graph.addVertex("sanabel");
      graph.addVertex("ahmad");
      graph.addVertex("tareq");
      graph.addVertex("yasmeen");
      graph.addVertex("kamleh");
      graph.addVertex("jamal");
      graph.addEdge("jamal", "kamleh");
      graph.addEdge("kamleh", "sanabel");
      graph.addEdge("sanabel", "yasmeen");
      graph.addEdge("tareq", "ahmad");
      graph.addEdge("ahmad", "yasmeen");
      graph.addEdge("tareq", "yasmeen");
      System.out.println(" print vertex in the graph: "+graph.getAdjVertices());
      System.out.println(" size (num of vertex ) in graph: "+graph.size());
      System.out.println(" get the Neighbors in graph: "+graph.getNeighborsForVertex("jamal"));
      System.out.println(" get the Neighbors in graph: "+graph.getNeighborsForVertex("sanabel"));
      System.out.println(" get the Neighbors in graph: "+graph.getNeighborsForVertex("ahmad"));

           /////////////////////cc36///////////////////////////
//Pandora, Arendelle, Metroville,
// Monstroplolis, Narnia, Naboo
    Graph graph2 = new Graph();

    graph.addVertex("Pandora");
    graph.addVertex("Arendelle");
    graph.addVertex("Metroville");
    graph.addVertex("Monstroplolis");
    graph.addVertex("Narnia");
    graph.addVertex("Naboo");

    graph.addEdge("Pandora", "Arendelle");
    graph.addEdge("Arendelle", "Metroville");
    graph.addEdge("Arendelle", "Monstroplolis");
    graph.addEdge("Metroville", "Narnia");
    graph.addEdge("Monstroplolis", "Metroville");
    graph.addEdge("Naboo", "Narnia");
    graph.addEdge("Naboo", "Metroville");
    graph.addEdge("Naboo", "Monstroplolis");

    System.out.println(" print graph Breadth First: "+graph.graphBreadthFirst(graph,"Pandora"));
    System.out.println(" print graph Breadth First: "+graph.graphBreadthFirst(graph,"Arendelle"));


    }

}
