import java.util.List;
import java.util.Vector;
import sun.security.provider.certpath.Vertex;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
  public static void main(String[] args) {

      Graph graph = new Graph();

      graph.addVertex("sanabel");
      graph.addVertex("ahmad");
      graph.addVertex("tareq");
      graph.addVertex("yasmeen");
      graph.addVertex("kamleh");
      graph.addVertex("jamal");
      graph.addEdge("jamal", "kamleh");
      graph.addEdge("kamleh", "sanabel");
      graph.addEdge("sanabel", "yasmeen");
      graph.addEdge("tareq", "ahmad");
      graph.addEdge("ahmad", "yasmeen");
      graph.addEdge("tareq", "yasmeen");
      System.out.println(" print vertex in the graph: "+graph.getAdjVertices());
      System.out.println(" size (num of vertex ) in graph: "+graph.size());
      System.out.println(" get the Neighbors in graph: "+graph.getNeighborsForVertex("jamal"));
      System.out.println(" get the Neighbors in graph: "+graph.getNeighborsForVertex("sanabel"));
      System.out.println(" get the Neighbors in graph: "+graph.getNeighborsForVertex("ahmad"));

    }

}
