/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeChallenge7;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
      int[] keys = { 1, 3, 8, 2};
      Node head = null;
      System.out.print("head");
      for (int i = keys.length-1; i >=0 ; i--) {
        head = new Node(keys[i], head);
        int k = 3;
        Node node = kLocation(head, k);

        if (node != null) {
          System.out.print(" ["+node.data+"] -> ");
        }
      }
      System.out.print("x");
    }
    public static Node kLocation(Node head , int k){
        Node current= head;
        if(current == null){
          return null;
        }
      for (int i = 0; current!=null & i<k; i++) {
        current=current.next;
      }
      while(current != null){
        head = head.next;
        current = current.next;
      }
      return head;
    }
}
