/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {
  @Test
  void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }

  @Test public void testInsert() {
    LinkedList test = new LinkedList();
    test.insert(5);
    int data1 = 5;
    assertNotNull(data1, test.insert(5));
  }
  @Test  void testAdd() {
    LinkedList test = new LinkedList();

    test.add(5);
    test.add(8);
        assertNotNull(5,test.add(5));
  }

  @Test  void testIncludes(){
    LinkedList test = new LinkedList();
    test.insert(14);
    test.insert(2);
    test.insert(21);
    int data1 = 8;
    int data2 = 14;
    assertEquals(false, test.includes(data1));
    assertEquals(true, test.includes(data2));
  }

@Test  void testTostring(){
  LinkedList test = new LinkedList();
  test.insert(2);
  test.insert(22);
  test.insert(222);
    assertEquals("{2} ->{22} ->{222} ->NULL" , test.tostring());

}
@Test void testAppend(){
  LinkedList test = new LinkedList();
  test.append(2);
  test.append(22);
  test.append(222);
  assertEquals("{2} ->{22} ->{222} ->NULL" , test.tostring());

}
  @Test void testInsertBefore(){
    LinkedList test = new LinkedList();
    test.append(2);
    test.append(22);
    test.append(222);
    test.insertBefore(222,111);
    assertEquals("{2} ->{22} ->{222} ->NULL" , test.tostring());

  }
  @Test void testInsertAfter(){
    LinkedList test = new LinkedList();
    test.append(2);
    test.append(22);
    test.append(222);
    test.insertAfter(222,2222);
    assertEquals("{2} ->{22} ->{222} ->NULL" , test.tostring());

  }
}
