/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        LinkedList test = new LinkedList();

     //insert in the end
      test.insert(1);
      test.insert(66);
      //added in the first
      test.add(10);
      test.add(30);
      test.add(11);
      test.add(21);

      test.includes(5);
      test.tostring();

      test.append(3);
      test.insertBefore(1,3);
      test.insertAfter(11,5);
    }

    }

