/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
    @Test
    public void testSortDifferentValue(){
      int [] array = {2,8,52,74,65,3};
      InsertSort test =new InsertSort();
      test.sortArray(array);
//      assertTrue("should return true",insertSort.sortArray());
      assertEquals("[2, 3, 8, 52, 65, 74]", Arrays.toString(array));
    }
    @Test
  public void testSortRepetition(){
      int [] array = {2,8,2,74,65,3,2};
      InsertSort test =new InsertSort();
      test.sortArray(array);
      assertEquals("[2, 2, 2, 3, 8, 65, 74]", Arrays.toString(array));
    }
  @Test
  public void testSortminusValue(){
    int [] array = {2,-8,2,-2,3,55};
    InsertSort test =new InsertSort();
    test.sortArray(array);
    assertEquals("[-8, -2, 2, 2, 3, 55]", Arrays.toString(array));
  }
}
